### ISSUE TITLE
Export function: attached files and videos are not exported

### ISSUE THREAD

**Issue by Pedrotheplant** [nikobojs/manuscrape_electron#34] opened 2023-10-18 08:47 UTC

**Comment by nikobojs** [comment] 2023-10-18 08:49
Thanks. This is in progress :+1:

**Comment by nikobojs** [comment] 2023-10-18 09:02
Also, its a duplicate of: https://github.com/nikobojs/manuscrape_electron/issues/17
Closing

**Closed as completed by nikobojs** 2023-10-18 09:02 UTC
Labels: enhancement
